const FETCH_MESSAGES_PENDING = 'FETCH_MESSAGES_PENDING';
const FETCH_MESSAGES_SUCCESS = 'FETCH_MESSAGES_SUCCESS';
const FETCH_MESSAGES_ERROR = 'FETCH_MESSAGES_ERROR';

export default {
  FETCH_MESSAGES_PENDING, FETCH_MESSAGES_SUCCESS, FETCH_MESSAGES_ERROR,
};
