const FETCH_MESSAGES_REQUEST = "FETCH_MESSAGES_REQUEST";
const FETCH_MESSAGES_SUCCESS = "FETCH_MESSAGES_SUCCESS";
const FETCH_MESSAGES_FAILURE = "FETCH_MESSAGES_FAILURE";

const REMOVE_MESSAGE = "REMOVE_MESSAGE";
const ADD_MESSAGE = "ADD_MESSAGE";
const LIKE_MESSAGE = "LIKE_MESSAGE";
const UPDATE_MESSAGE = "UPDATE_MESSAGE";

export default {
  FETCH_MESSAGES_REQUEST,
  FETCH_MESSAGES_SUCCESS,
  FETCH_MESSAGES_FAILURE,
  REMOVE_MESSAGE,
  ADD_MESSAGE,
  LIKE_MESSAGE,
  UPDATE_MESSAGE
};
