const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST';
const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE';

const DELETE_USER_REQUEST = 'DELETE_USER_REQUEST';
const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST';
const ADD_USER_REQUEST = 'ADD_USER_REQUEST';

export default {
  FETCH_USERS_FAILURE,
  FETCH_USERS_REQUEST,
  FETCH_USERS_SUCCESS,
  DELETE_USER_REQUEST,
  UPDATE_USER_REQUEST,
  ADD_USER_REQUEST
};
