const FETCH_MESSAGE_REQUEST = 'FETCH_MESSAGE_REQUEST';
const FETCH_MESSAGE_SUCCESS = 'FETCH_MESSAGE_SUCCESS';
const FETCH_MESSAGE_FAILURE = 'FETCH_MESSAGE_FAILURE';

export default { FETCH_MESSAGE_REQUEST, FETCH_MESSAGE_FAILURE, FETCH_MESSAGE_SUCCESS };
