const SHOW_MODAL = 'SHOW_MODAL';
const HIDE_MODAL = 'HIDE_MODAL';
const SET_CURRENT_USER_ID = 'SET_CURRENT_USER_ID';
const DROP_CURRENT_USER_ID = 'DROP_CURRENT_USER_ID';

export default {
  SHOW_MODAL,
  HIDE_MODAL,
  SET_CURRENT_USER_ID,
  DROP_CURRENT_USER_ID
};
